/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class Attendance {
    constructor() {
        this.attendanceId = undefined;
        this.sessionId = "";
        this.studentId = "";
        this.className = "";
        this.courseName = "";
        this.date = "";
        this.period = "";
        this.status = "";
    }

    setAttendanceId(attendanceId) {
        this.attendanceId = attendanceId;
    }

    getAttendanceId() {
        return this.attendanceId;
    }

    setSessionId(sessionId) {
        this.sessionId = sessionId;
    }

    getSessionId() {
        return this.sessionId;
    }

    setStudentId(studentId) {
        this.studentId = studentId;
    }

    getStudentId() {
        return this.studentId;
    }

    setClassName(className) {
        this.className = className;
    }

    getClassName() {
        return this.className;
    }

    setCourseName(courseName) {
        this.courseName = courseName;
    }

    getCourseName() {
        return this.courseName;
    }

    setDate(date) {
        this.date = date;
    }

    getDate() {
        return this.date;
    }

    setPeriod(period) {
        this.period = period;
    }

    getPeriod() {
        return this.period;
    }

    setStatus(status) {
        this.status = status;
    }

    getStatus() {
        return this.status;
    }
}

Attendance.className = 'Attendance';

export {Attendance}