/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class ClassInfo {
    constructor() {
        this.className = undefined;
    }

    setClassName(className) {
        this.className = className;
    }

    getClassName() {
        return this.className;
    }
}

ClassInfo.className = 'ClassInfo';

export {ClassInfo}